server:
  port: 8997

eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8765/eureka/
      #defaultZone: http://peer1:8761/eureka/,http://peer2:8762/eureka/
  #      defaultZone:  http://eureka.tae-tea.net:8085/eureka/
  instance:
    prefer-ip-address: true # 优先注册IP地址而不是hostname
#  healthcheck:
#    enabled: true # 启用健康检查,注意:需要引用spring boot actuator

spring:
  application:
    name: cloud-from-dubbo




  # redis配置
  redis:
    host: 127.0.0.1
    port: 6379
    password:

  datasource:
    name: test
    url: jdbc:mysql://59.110.228.110:3309/test?useUnicode=true&characterEncoding=utf-8&useSSL=false
#    url: jdbc:mysql://59.110.228.110:3309/test
    username: root
    password: 4^1y!*$UCtSi)]ZV
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20
    mybatis:
      type-aliases-package:  domain

      data:
        mongodb:
          uri: mongodb://localhost:27017/test

#  data:
#    mongodb:
#      host:localhost
#      port:27017
#      database:test
#      username:
#      password:




logging:
  level:
    com:
      yestae:
        dao: debug