server:
  port: 80

# mysql
spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    #MySQL\u914d\u7f6e
    driverClassName: com.mysql.jdbc.Driver
#    url: jdbc:mysql://192.168.100.220:3306/yestae_core?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
#    username: yestae_core
#    password: VCT0YeIfx8asw2
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://59.110.228.110:3306/tea_admin_mall?allowMultiQueries=true&useUnicode=true&characterEncoding=UTF-8&useSSL=false
    username: tea_admin_mall
    password: euRyC7S1Il75AiI
    #oracle\u914d\u7f6e
    #    driverClassName: oracle.jdbc.OracleDriver
    #    url: jdbc:oracle:thin:@47.100.206.162:1521:xe
    #    username: oracle
    #    password: 123456
    #SQLServer\u914d\u7f6e
    #    driverClassName: com.microsoft.sqlserver.jdbc.SQLServerDriver
    #    url: jdbc:sqlserver://192.168.10.10:1433;DatabaseName=renren_fast
    #    username: sa
    #    password: 123456
    #PostgreSQL\u914d\u7f6e
  #    driverClassName: org.postgresql.Driver
  #    url: jdbc:postgresql://192.168.10.10:5432/renren_fast
  #    username: postgres
  #    password: 123456
  jackson:
    time-zone: GMT+8
    date-format: yyyy-MM-dd HH:mm:ss
  resources:
    static-locations: classpath:/static/,classpath:/views/


mybatis:
  mapperLocations: classpath:mapper/**/*.xml


pagehelper:
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql


#\u6307\u5b9a\u6570\u636e\u5e93\uff0c\u53ef\u9009\u503c\u6709\u3010mysql\u3001oracle\u3001sqlserver\u3001postgresql\u3011
renren:
  database: mysql

